name: Deploy Infra and App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_VAR_ami_id: ami-0c02fb55956c7d316
      TF_VAR_instance_type: t2.micro
      ANSIBLE_HOST_KEY_CHECKING: "False"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        working-directory: ./infra/terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./infra/terraform
        run: terraform apply -auto-approve

      - name: Get public IP from Terraform
        id: get_ip
        working-directory: ./infra/terraform
        run: |
          IP=$(terraform output -raw instance_public_ip)
          echo "INSTANCE_IP=$IP" >> $GITHUB_ENV

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible sshpass

      - name: Add SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Create dynamic Ansible inventory
        run: |
          echo "[web]" > ./ansible/inventory.ini
          echo "$INSTANCE_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ./ansible/inventory.ini

      - name: Run Ansible playbook
        working-directory: ./ansible
        run: ansible-playbook -i inventory.ini playbook.yml
